# -*- coding: utf-8 -*-
"""Q2 Ramyathambabattula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/189mO1JmAxlD5A0MccWLwJF1HJvA8xS_4
"""

import pandas as pd
import matplotlib.pyplot as plt

# Reading the CSV file
student_performance_data = pd.read_csv("StudentsPerformance.csv")

# Visualization Scatter Plot
plt.scatter(student_performance_data['math score'], student_performance_data['reading score'], c='yellow')
plt.title("Visualization scatterplot for Math Score Vs Reading Score")
plt.xlabel("Math Score")
plt.ylabel("Reading Score")
plt.show()

# Visualization Sunflower
plt.scatter(student_performance_data['writing score'], student_performance_data['reading score'], c='green', marker='o')
plt.title("Visualization for Sunflower Writing Score Vs Reading Score")
plt.xlabel("Writing Score")
plt.ylabel("Reading Score")
plt.show()

# Visualization Histogram Reading Score
plt.hist(student_performance_data['reading score'], color='pink', bins=30)
plt.xlabel("Reading Score")
plt.title("Visualization for Histogram Reading Score")
plt.show()

#  Visualization Histogram process for Writing Score
plt.hist(student_performance_data['writing score'], color='green', bins=30)
plt.xlabel("Writing Score")
plt.title("Visualization Histogram process for Writing Score")
plt.show()

# Visualization process for Line Ploting
plt.plot(student_performance_data['math score'], student_performance_data['reading score'], 'g+')
plt.title("Visualization Line Ploting for Math Score Vs Reading Score")
plt.xlabel("Math Score")
plt.ylabel("Reading Score")
plt.show()

# The Barplot Visualization process
plt.bar(range(len(student_performance_data)), student_performance_data['writing score'], color='purple')
plt.xlabel("Student Index")
plt.ylabel("Writing Score")
plt.title("Barplot Visualization for Writing Score")
plt.show()

# Boxplot Visualization process for Reading Score
plt.boxplot(student_performance_data['reading score'], vert=False, patch_artist=True, boxprops=dict(facecolor='lightblue'))
plt.xlabel("Reading Score")
plt.title("Boxplot Visualization of Reading Score")
plt.show()