# -*- coding: utf-8 -*-
"""PDS_Assingnment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uFt5Z4Xi-hq2JkRTCLZRdf7O-Ne4QtS2
"""

import pandas as pd
from datetime import datetime

# Load dataset
data = pd.read_csv('train.csv')

# a) Handling Missing Values and empty strings in all the columns
missing_values = data.isnull().sum()

# Impute missing values and handle empty strings for numerical columns
numerical_columns = ['Year', 'Mileage', 'Engine', 'Power', 'New_Price']
categorical_columns = ['Fuel_Type', 'Transmission']

for column in numerical_columns:
    # Identify the  handle non-numeric characters by changing them with NaN
    data[column] = pd.to_numeric(data[column], errors='coerce')
    data[column].fillna(data[column].mean(), inplace=True)

for column in categorical_columns:
    data[column].fillna(data[column].mode()[0], inplace=True)

# b) Removing Units, No need to clear the units again, we have already completed it while handling missing values.

# c) Change the categorical variables (“Fuel_Type” and “Transmission”) into numerical one hot/Encoding for Categorical Variables
data = pd.get_dummies(data, columns=['Fuel_Type', 'Transmission'], prefix=['Fuel_Type', 'Transmission'])

# d) Create one more New Feature - Current Age of the Car
current_year = datetime.now().year
data['Current_Age'] = current_year - data['Year']

# Display the first few rows of the changed dataset values.
print(data.head())

# Store the processed dataset.
data.to_csv('processed_train.csv', index=False)